### ISSUE TITLE
Dumping any Yasmin object seems to dump entire Yasmin configuration

### ISSUE THREAD

**Issue by joelwmale** [CharlotteDunois/Yasmin#112]
I am trying to do a dump (dd in laravel, similar to symfonys https://github.com/symfony/var-dumper) of the highest role for the messages member, code looks like:

`dd($message->member->getHighestRole());`

But the dd returns 2.7k lines of text, which seems to be information about the entire guild, and not the `Role` that the function is supposed to be returning as per docs..

An example dd looks like:

```php
$test = [
    'foo' => 'bar'
];

dd($test);
```

prints out:

```php
array:1 [
  "foo" => "bar"
]
```

It is perhaps the client configuration, although I am just using the defaults as recommended by the documentation:

```php
$this->loop = \React\EventLoop\Factory::create();
$this->client = new \CharlotteDunois\Yasmin\Client(array(
    'ws.disabledEvents' => array(
        /* We disable the TYPING_START event to save CPU cycles, we don't need it here in this example. */
        'TYPING_START'
    )
), $this->loop);
```

Any ideas? My end goal is to get a list of all members with no roles and kick them if they joined over 24 hours ago. The logic for this is not hard, but determining what kind of data Yasmin offers is, when I can't dump the data to look at the structure.

**Comment by CharlotteDunois** [comment]
The role contains a reference to the client and to the guild. Since there are many references **you can't** just dump objects without having a depth limiter.

The old WIP gitbook has a special notice for that.
![grafik](https://user-images.githubusercontent.com/4529744/58793253-0b53c880-85f6-11e9-9346-a77c3c243676.png)

If you want to dump a Yasmin object, use `var_dump` with Xdebug and limit the depth to <= 3 (3 is default, set it to whatever you're comfortable with).

Since you're only dumping in development, the performance impact due to Xdebug doesn't matter. You can always only load the extension on executing the PHP binary using the `-d` command line argument.

**Comment by joelwmale** [comment]
Ah. Alright, thanks for letting me know!
