### ISSUE TITLE
Old channel member are not updated (probably VoiceStateUpdate.php)

### ISSUE THREAD

**Issue by ChalyFlavour** [CharlotteDunois/Yasmin#137]
If a user changes his/her voicechannel, the voiceStateUpdate event is triggered correctly and both parameters (newMember and oldMember) are set, but the user is still listed in his previous channel (guild->channels->member collection).

If a user disconnects his/her voicechannel, the voiceStateUpdate is triggered as well. In this case the member is not listed anymore in his previous channel (guild->channels->member collection).

I expected the old channel member collection not listing the user anymore as he isn't in his $oldChannel any longer.

- [ x ] I have also tested the issue on latest master with commit hash:

**Comment by ChalyFlavour** [comment]
I "hotfixed" it on my Livia instance by having an voiceStateUpdate event handler that deletes the member from his old channel. I would appreciate it if this would be done by the VoiceStateUpdate.php
 ```
                   if(is_object($oldMember) && $oldMember->voiceChannel)
                    {
                        $oldMember->voiceChannel->members->delete($oldMember->id);
                    }
```

**Comment by CharlotteDunois** [comment]
This bug is created by not updating the proper channel. We're removing the member from the same channel as the member is joining and then adding the user back. Of course this is wrong.
https://github.com/CharlotteDunois/Yasmin/blob/35c94be2ccef084addffe749f63bbda6cc5fdd11/src/WebSocket/Events/VoiceStateUpdate.php#L102

If we instead do the same thing as in the leaving voice channel branch, this bug would be fixed.
https://github.com/CharlotteDunois/Yasmin/blob/35c94be2ccef084addffe749f63bbda6cc5fdd11/src/WebSocket/Events/VoiceStateUpdate.php#L63-L65

Would you like to create a PR for this?
