### ISSUE TITLE
Replacing Guzzle with a fully async HTTP client

### ISSUE THREAD

**Issue by WyriHaximus** [CharlotteDunois/Yasmin#52]
Been peeking at the code at noticed you've been using Guzzle to send requests async. This way isn't fully async, would you be open for a PR that swaps out Guzzle with a HTTP client that is fully compatible but works fully async?

**Comment by CharlotteDunois** [comment]
My choice using Guzzle was due to Guzzle being able to delegate the HTTP requests away to `curl_multi`, which has the nice effect of being completely free during cURL handling the HTTP request, unlike other asynchronous HTTP clients fully implemented in PHP.

I'm fully aware that GuzzleHTTP isn't fully asynchronous, due to the way it has to handle `curl_multi` (and the way I had to implement it into ReactPHP). I'm open to such a PR if the new HTTP client doesn't introduce nasty side-effects and performs better than the current HTTP client combination. As a result of this PR, depending on the HTTP client, this may be a breaking change of the public API (URLHelpers util).
