### ISSUE TITLE
Is there a way to get the data outside of promise ?

### ISSUE THREAD

**Issue by Dylvn** [CharlotteDunois/Yasmin#90]
Hi

```php
$promise = $message->client->fetchUser($discordId);
$promise->then(function ($user) {
    return $user;
})
``` 

How can I get access to $user outside ?

**Comment by CharlotteDunois** [comment]
Read this to get to know what promises are and how you use them: https://sergeyzhuk.me/2017/06/16/phpreact-promises/

**Comment by Animeshz** [comment]
You simply cannot because the thing inside the promise is never been known when it will be happen. Promise execute asynchronously which means it never happened at the time of the execution, it is just queued, time for the execution is unknown, it can execute anytime once the old items in the queue has been executed. Tip: Do whatever you wanted to inside the promise, if you have multiple promises, just take a look at Promise\all() function.
